version: '4.2'

services:
  app:
    container_name: app
    build: ./App
    ports:
      - "8000:8000"
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: postgres
      PG_HOST: db
      PG_PORT: 5432
    depends_on:
      - db

  userapp:
    container_name: userapp
    build: ./UserApp
    ports:
      - "8001:8000"
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: postgres
      PG_HOST: db
      PG_PORT: 5432
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
  

volumes: 
  pgdata: {}
